# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects\new(1)\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 370)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 31, 16))
        self.label.setObjectName("label")
        self.sort = QtWidgets.QLineEdit(Form)
        self.sort.setGeometry(QtCore.QRect(120, 60, 331, 20))
        self.sort.setObjectName("sort")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 21))
        self.label_2.setObjectName("label_2")
        self.step_obj = QtWidgets.QLineEdit(Form)
        self.step_obj.setGeometry(QtCore.QRect(120, 100, 331, 20))
        self.step_obj.setObjectName("step_obj")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 111, 21))
        self.label_3.setObjectName("label_3")
        self.type = QtWidgets.QComboBox(Form)
        self.type.setGeometry(QtCore.QRect(120, 140, 331, 22))
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 91, 21))
        self.label_4.setObjectName("label_4")
        self.vkus = QtWidgets.QLineEdit(Form)
        self.vkus.setGeometry(QtCore.QRect(120, 180, 331, 20))
        self.vkus.setObjectName("vkus")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 220, 31, 21))
        self.label_5.setObjectName("label_5")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(120, 220, 331, 20))
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 260, 41, 20))
        self.label_6.setObjectName("label_6")
        self.obyom = QtWidgets.QLineEdit(Form)
        self.obyom.setGeometry(QtCore.QRect(120, 260, 331, 20))
        self.obyom.setObjectName("obyom")
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setGeometry(QtCore.QRect(180, 310, 141, 31))
        self.ok.setObjectName("ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить/Редактировать"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Молотый/В зёрнах"))
        self.type.setItemText(0, _translate("Form", "Молотый"))
        self.type.setItemText(1, _translate("Form", "В зёрнах"))
        self.label_4.setText(_translate("Form", "Описание вкуса"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объём"))
        self.ok.setText(_translate("Form", "OK"))
